ChainID = 1999
CoinPrecision = 100000000
CoinSymbol = "gls"
Title = "pos33"
version = "1.0.0.1"

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
logConsoleLevel = "error"
loglevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"

[blockchain]
# 区块数据目录
batchsync = false
dbCache = 512
dbPath = "datadir"
disableBlockBroadcast = false
disableShard = true
enablePushSubscribe = false
enableReExecLocal = false
enableReduceLocaldb = true
enableTxQuickIndex = true
isParaChain = false
isRecordBlockSequence = true
singleMode = false

[mempool]
maxTxNumPerAccount = 1000
poolCacheSize = 1024000

[p2p]
dbPath = "datadir/addrbook"
grpcLogFile = "grpc33.log"

[p2p.sub.dht]
# 分组通道, 同一个网络的channel必须相同
channel = 15
# p2p服务端口
port = 13801
#可以自定义设置连接节点
seeds = []

[p2p.sub.dht.broadcast]
disableBatchTx = true
minLtBlockSize = 100

[rpc]
certFile = "cert.pem"
enableTLS = false
grpcBindAddr = ":9902"
grpcFuncWhitelist = ["*"]
jrpcBindAddr = ":9901"
jrpcFuncWhitelist = ["*"]
keyFile = "key.pem"
whitelist = ["*"]

[rpc.sub.eth]
enable = true
httpAddr = "0.0.0.0:8547"
httpApi = ["eth", "web3", "personal", "admin", "net"]
# websocket 绑定地址
wsAddr = "0.0.0.0:8548"
wsApi = ["eth", "web3", "personal", "admin", "net"]

[consensus.sub.pos33]
bootPeers = []
issueTotal = 2000000000
listenPort = 10801

[store]
dbPath = "datadir/kvmvcc"

[wallet]
coinType = "gls"
dbPath = "wallet"

[health]
listenAddr = "localhost:8708"
